# Generated by Django 4.1.4 on 2023-03-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
    ]
