# Generated by Django 4.1.4 on 2023-03-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='image1.jpg', max_length=50),
        ),
    ]
