# Generated by Django 4.1.4 on 2023-03-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
