# Generated by Django 4.1.4 on 2023-03-24 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_remove_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='addressDetail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='county',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postcode',
        ),
        migrations.CreateModel(
            name='MyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('neighborhood', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('postcode', models.IntegerField()),
                ('addressDetail', models.TextField(max_length=60)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
