# Generated by Django 4.1.4 on 2023-03-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_addressdetail_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaddress',
            name='apartmentNo',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='myaddress',
            name='binaNo',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='myaddress',
            name='flights_up',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
